/*PROCEDURES*/

CREATE DATABASE ESCOLA;

CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	HORAS INT (3) NOT NULL,
	VALOR FLOAT (10,2) NOT NULL
);

SHOW TABLES;

INSERT INTO CURSOS VALUES(NULL,'JAVA',30,500.00);
INSERT INTO CURSOS VALUES(NULL,'FUNDAMENTOS DE BANCOS DE DADOS',40,700.00);

SELECT * FROM CURSOS;

+---------+--------------------------------+-------+--------+
| IDCURSO | NOME                           | HORAS | VALOR  |
+---------+--------------------------------+-------+--------+
|       1 | JAVA                           |    30 | 500.00 |
|       2 | FUNDAMENTOS DE BANCOS DE DADOS |    40 | 700.00 |
+---------+--------------------------------+-------+--------+

DELIMITER #

STATUS

CREATE PROCEDURE CAD_CURSO	(P_NOME VARCHAR(30),
							 P_HORAS INT(3),
							 P_PRECO FLOAT(10,2))
BEGIN
	INSERT INTO CURSOS VALUES(NULL,P_NOME,P_HORAS,P_PRECO);
END
#

CALL CAD_CURSO('BI SQL SERVER', 35,3000.00);
CALL CAD_CURSO('POWER BI', 20,1000.00);
CALL CAD_CURSO('TABLEAU', 40,1200.00);

/*EXERCICIO CRIAR PROCEDURE PARA CONSULTAR CURSOS*/

DELIMITER #

CREATE PROCEDURE CONSULTA_CURSOS(P_NOMECURSO)
BEGIN
	SELECT * FROM CURSOS
	WHERE NOME LIKE P_NOMECURSO;
END
#
DELIMITER ;


/*PROCURANDO CONSTRAINTS NO DICIONARIO DE DADOS*/
USE INFORMATION_SCHEMA;
SHOW TABLES;
DESC TABLE_CONSTRAINTS;

SELECT 	CONSTRAINT_SCHEMA AS "BANCO",
		TABLE_NAME AS "TABELA",
		CONSTRAINT_NAME AS "NOME TABELA",
		CONSTRAINT_TYPE AS "TIPO"
		FROM TABLE_CONSTRAINTS
		WHERE CONSTRAINT_SCHEMA = 'comercio';