/*UPDATE, INSERT DELETE - EM VIEWS*/
INSERT INTO V_RELATORIO VALUES(
'ANDREIA','F','ANDREIA@UOL.COM.BR','CEL','873547864','CENTRO','VITORIA','ES'
);
/*
VIEWS COM JOIN NAO PERMITEM INSERT E DELETE, SOMENTE UPDATE.
VIEWS SEM JOIN PODEMOS FAZER AS 3 OPERACOES UPDATE, DELETE E INSERT
*/