use comercio;

desc cliente;
desc telefone;
desc endereco;

/*relatorio geral de clientes*/

select 	C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, 
		E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO,
        T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

/*Relatorio de homens*/
select 	C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, 
		E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO,
        T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
where C.sexo = 'm';

/*Corrigindo IDs com sexo incorreto 12, 13, 18, 19 */
select * from cliente
where idcliente in(12,13,18,19); 

update cliente set sexo = 'F'
where idcliente in (12,13,18,19);

/*Relatorio de mulheres*/
select 	C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, 
		E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO,
        T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
where C.sexo = 'm';

/*alterando o cliente com sexo errado id = 16*/
update cliente set sexo = 'M'
where idcliente = 16;

/*Quantidade de homens e mulheres*/
select sexo, count(*) as quantidade
from cliente
group by sexo;

/* IDS E EMAIL DAS MULHERES QUE MOREM NO CENTRO DO RIO DE JANEIRO E NAO TENHAM CELULAR */

SELECT C.IDCLIENTE, C.EMAIL, C.SEXO, C.NOME,T.TIPO, E.CIDADE, E.BAIRRO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE C.SEXO = 'f'
AND E.BAIRRO = 'CENTRO' AND E.CIDADE = 'RIO DE JANEIRO'
AND T.TIPO IN('RES', 'COM');

/* PARA UMA CAMPANHA DE MARKETING, O SETOR SOLICITOU UM
RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR 
DOS CLIENTES QUE MORAM NO ESTADO DO RIO DE JANEIRO 
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR */

SELECT C.NOME, C.EMAIL, T.NUMERO AS CELULAR
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE TIPO = 'CEL'AND ESTADO = 'RJ';


/* PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM
RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR 
 DAS MULHERES QUE MORAM NO ESTADO DE SÃO PAULO 
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR */
SELECT C.NOME, C.EMAIL, T.NUMERO AS CELULAR
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F' AND ESTADO = 'SP';