/*NOME EMAILS NUMERO E ESTADO*/
SELECT  C.NOME, 
		C.EMAIL,
        E.ESTADO,
        T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

/*FUNCAO IFNULL - RETORNA VALRES VAZIOS COM A INFORMACAO QUE EU QUIZER*/

SELECT  C.NOME, 
		IFNULL(C.EMAIL, 'NÃO TEM EMAIL') AS 'E-MAIL',
        E.ESTADO,
        T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;




