/*QUERY DE EXEMPLO PRA VIEWS*/

SELECT 	C.NOME,
		C.SEXO,
       ifnull(C.EMAIL, 'NAO TEM EMAIL') AS 'E-MAIL',
        T.TIPO,
        T.NUMERO,
        E.BAIRRO,
        E.CIDADE,
        E.ESTADO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

/*CRIANDO A VIEW*/
CREATE VIEW RELATORIO AS
SELECT 	C.NOME,
		C.SEXO,
       ifnull(C.EMAIL, 'NAO TEM EMAIL') AS 'E-MAIL',
        T.TIPO,
        T.NUMERO,
        E.BAIRRO,
        E.CIDADE,
        E.ESTADO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

/*CHAMANDO A VIEW*/
SELECT * FROM RELATORIO;
DESC RELATORIO;

DROP VIEW RELATORIO;

/*RECOMENDADO COLOCAR UM PREFIXO NA CRIACAO DA VIEW PRA DIFERENCIAR UMA VIEW DAS TABELAS*/
CREATE VIEW V_RELATORIO AS
SELECT 	C.NOME,
		C.SEXO,
       ifnull(C.EMAIL, 'NAO TEM EMAIL') AS 'E-MAIL',
        T.TIPO,
        T.NUMERO,
        E.BAIRRO,
        E.CIDADE,
        E.ESTADO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

SHOW TABLES;
/*POODEMOS FAZER UMA QUERY EM CIMA DE UMA VIEW*/
SELECT NOME, NUMERO, ESTADO
FROM V_RELATORIO;







